# Generated by Django 4.2.19 on 2025-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "verbose_name": " restaurant",
                "verbose_name_plural": "restaurant list",
            },
        ),
        migrations.AddField(
            model_name="restaurant",
            name="category",
            field=models.CharField(
                choices=[
                    ("chinese", "Chinese"),
                    ("western", "Western"),
                    ("fastfood", "Fastfood"),
                    ("hotpot", "Hotpot"),
                    ("japanese", "Japanese"),
                    ("cafe", "Cafe"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Restaurant category",
            ),
        ),
    ]
