# Generated by Django 4.2.19 on 2025-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_options_restaurant_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={},
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="address",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Restaurant image",
                null=True,
                upload_to="restaurant_images/",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(
                default=0.0, help_text="Latitude of the restaurant"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(
                default=0.0, help_text="Longitude of the restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.CharField(
                choices=[
                    ("chineseFood", "Chinese Food"),
                    ("fastFood", "Fast Food"),
                    ("drinkAndCoffee", "Drink And Coffee"),
                    ("sushi", "Sushi"),
                    ("groceries", "Groceries"),
                ],
                default="other",
                max_length=20,
                verbose_name="Restaurant category",
            ),
        ),
    ]
