# Generated by Django 4.2.19 on 2025-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0003_alter_restaurant_options_remove_restaurant_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="minimum_order",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
