# Generated by Django 4.2.19 on 2025-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restaurant_minimum_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="password",
            field=models.CharField(default="a", max_length=128),
        ),
    ]
