# Generated by Django 4.2.19 on 2025-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_restaurant_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="username",
            field=models.CharField(default="a", max_length=128),
        ),
    ]
