# Generated by Django 4.2.19 on 2025-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_restaurant_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
