# Generated by Django 4.2.19 on 2025-03-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_restaurant_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="username",
            field=models.CharField(default="a", max_length=128, unique=True),
        ),
    ]
