# Generated by Django 4.2.19 on 2025-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_alter_restaurant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defaults/default.png",
                null=True,
                upload_to="menu_images/",
            ),
        ),
    ]
