# Generated by Django 4.2.19 on 2025-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
