# Generated by Django 4.2.19 on 2025-03-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_address_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="is_default",
        ),
    ]
