# Generated by Django 4.2.19 on 2025-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_created_at_alter_order_items_delete_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
