# Generated by Django 4.2.19 on 2025-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "Preparing"), ("C", "Finished"), ("X", "Awaiting")],
                default="X",
                max_length=1,
            ),
        ),
    ]
